config/routes.rb
Rails.application.routes.draw do
  root to: "messages#index"
  resources :messages, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  before_create :send_sms

  def initialize(attributes)
    @to = attributes[:to]
    @body = attributes[:body]
  end

private

  def send_sms(to, body)
    response = RestClient::Request.new(
      :method => :post,
      :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :To => to,
                    :From => ENV['FROM_PHONE_NUMBER'] }
    ).execute
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def new
    # @message = Message.new
  end

  def create
    message = Message.new({to: params[:to], body: params[:body]})
    # if message.save
      redirect_to root_path, notice: 'message sent!'
    # else
      # redirect_to new_messages_path, alert: 'fail!'
    # end
  end

  def show
    @message = Message.find(params[:id])
  end

private
  def message_params
    params.require(:message).permit(:to, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestClient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<h3>All Messages</h3>
<ul>
  <% @messages.each do |msg| %>
    <li><%= link_to msg.body, message_path(msg) %></li>
  <% end %>  
</ul>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h2>Send an SMS</h2>

<%= form_tag( "/messages", method: "post" ) do %>
  <div class="form-group">
    <%= label_tag "To" %><br>
    <%= telephone_field_tag :to, nil, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "Body" %><br>
    <%= text_field_tag :body, nil, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= submit_tag "Send", :class => "btn btn-default" %>
  </div>
<% end %>